### ISSUE TITLE
Feature request: Integration with Tasker

### ISSUE THREAD

**Issue by rawdr** [ssaqua/ProximityService#1]
Love the app for it's simplicity and usefulness. Would it be feasible to integrate with Tasker (https://tasker.dinglisch.net) for starting and disabling the service? Ideally you'd have the option of turning off proximity service while leaving the notification, OR disabling and removing the notification.

Thanks.

**Comment by ssaqua** [comment]
It should already be possible to start and stop the service with Tasker - when adding a task to a profile, use the launch app action and long press on Proximity Service to access StopActivity. Is this enough for what you had in mind?

I do agree that stopping and dismissing the notification with one action would be a good option. I could add another activity that does this and have it available as an extra action on the notification.
