### ISSUE TITLE
Bugged update 2.2.5

### ISSUE THREAD

**Issue by mstombs** [ssaqua/ProximityService#12]
Hi, your latest update doesn't save the screen off time, keeps reverting to 0, is there an archive of past apks so I can revert?

**Comment by ssaqua** [comment]
You can get all previous release APKs here https://github.com/ssaqua/ProximityService/releases

Thanks for bringing this to my attention, I can see where the bug causing this is and will be releasing a fix for it shortly. I don't believe using a past version will fix this as they're all likely to have the same bug.

**Comment by mstombs** [comment]
Oh, same issue with 2.2.3 now, how have I not suffered this before? The slider resets to 0 when you look at settings, Probably shouldn't look!  I have a new phone a Xiaomi withMIUI interface, have to set the settings app as a 'locked' process to stop it being closed when not in foreground

**Comment by ssaqua** [comment]
[v2.2.6](https://github.com/ssaqua/ProximityService/releases/tag/v2.2.6) is up on the releases page which should fix this. The update should be available on the Play Store soon.
