### ISSUE TITLE
'settings" option on notification causes device restart

### ISSUE THREAD

**Issue by puppykickr** [ssaqua/ProximityService#15]
I just tried out your app, and really like it.
When playing with it the first time, I saw that in addition to the 'Tap To Turn Off' notification from your app, there was also a 'Settings' notification that is presumably from my device.

I went ahead and tapped the 'Settings' option, as the app description stated that there were no settings, lol.

The device immediately restarted.

It is a ZTE 557VL running Nugat 7.1.1 OS.

I just wanted to bring this to your attention.

Actually, it can be very useful for me, as my volume and power keys are not functioning properly.

I already have found an app for the volume control, and I use Wave Up to turn the screen on from sleep.
Wave Up has a feature similar to your app (turning the screen off when covered), but it is very finicky, and does not work good with any of my devices.

I have not previously found any app to cause a restart like yours, so I might actually consider this a plus, lol.

I wonder if having Wave Up running (only as a way to turn the screen on from sleep) has anything to do with this restart thing happening?

**Comment by ssaqua** [comment]
🤔 Could you share a screenshot of the exact settings option that you pressed?

Apps don't typically have enough permission to reboot the device unless installed as a system app or configured to be a device admin app. In any case, there should be no way for this app to cause a reboot.

**Comment by puppykickr** [comment]
Yes, and yes.

I was perplexed as well, because I learned the same thing when I was searching for an app to do this very thing.

Like I said, for me, this is an added feature. But I also understand how it might not be for someone else.

I also forgot to mention that I am using Greenify. I dont know if that could have anything to do with this behavior.
I do NOT have your app 'Greenified', but Greenify is set to force stop any user app running in the bavkground (that does not have a notification) whenever the screen goes off.

Forgot to mention that earlier.

Will attempt the screenshot now.

**Comment by puppykickr** [comment]
Sorry, but I cannot achieve a screenshot of the notifications.

However, I did get an actual photo of it with another device.

Hopefully this is good enough, but the quality is low.
(Go ahead and attempt a photo of the screen on a different device, lol)

![IMG_20200707_222117_1_1](https://user-images.githubusercontent.com/44860287/86872131-3fbf7100-c0a1-11ea-88aa-dc159b3025f0.jpg)

**Comment by ssaqua** [comment]
Hmm yeah, that is indeed supposed to open the Settings screen for this app. I can't really comment on how all the other apps you mentioned would affect this - they really shouldn't.

As an alternative you may be able to access the Settings screen by long pressing the Proximity Service launcher icon > App Info > there should be some kind of settings cog or way to get there from this screen.

Sorry I probably can't help more than that unless this is a broad issue affecting a lot of users.

**Comment by puppykickr** [comment]
No problem- no reason to be sorry at all.
I was just posting this for general information.

Like I said, it is actually something that I can call a useable feature.

But also it could happen to someone else that night not have a use for it like me.

I am still interested to see what settings are available, even though the app works just fine as is.

Either way, looks like I get an extra, unexpected feature, lol.

Seriously, though- it is extremely difficult to get two (identical) of my devices to restart, so I can see this becoming quite handy.

I am a live sound engineer, and so I have multiple sound and EQ apps on my devices.
Android only allows one at a time to function, and that is fine, but sometimes it gets 'stuck' to where none of them will have any effect.
A restart is usually the quickest remedy, and for quite some time that has been a difficult option, because my power and volume buttons don't work well.

So a quick way to instigate a restart, and just by tapping a notification at that, is really a great thing for me.

Thank you for this app, and this little extra feature!

**Comment by puppykickr** [comment]
You are correct, on the app info page there is the settings gear.
Great!

Also, when reading the info in the settings, Iearned why Greenify remains inactive when your app activates- it is because the screen is still active, not actually sleeping.

This is a good thing, and it also should rule out Greenify as having any effect with this app's functions.

**Comment by puppykickr** [comment]
OK...
Something weird is going on.
Or, maybe better said, is that something weird is NOT going on anymore.

I just want to update you to the fact that I have installed your app onto a ZTE Maven 812 running 5.1.1, another ZTE 557VL running 7.1.1 (I have two of those, the issue occured on the first one.), and a Poblano VLE5 running 8.1.1.

It is working perfectly on all the devices.
And it is even working as intended on the first device, the one that initiated the issue.

For some reason, it is no longer resetting the device when I attempt to enter the settings.

I have no idea why, unless somehow using the settings icon on he app info page gave my device the right idea.

Anyway, thanks for your attention, and the app.

Case closed!
(I didn't close it myself, as I wanted to be sure you might see this post.)
