### ISSUE TITLE
Samsung Galaxy S20 proximity

### ISSUE THREAD

**Issue by Iworb** [ssaqua/ProximityService#16]
Unlike S10 series, proximity sensor in S20 works like a charm, but this service still counts this device as unsupported. Could we have an update?

**Comment by ssaqua** [comment]
I've added the S20 to supported devices, please check again in the Play Store.

**Comment by Iworb** [comment]
Got it. Tested on my device, but it doesn't work. Internal proximity test works great.
![image](https://user-images.githubusercontent.com/6623262/89780336-ec19ca80-db19-11ea-8ff6-a5aea0f1e178.png)
![image](https://user-images.githubusercontent.com/6623262/89780341-efad5180-db19-11ea-97c8-bc98a6159ff2.png)

It looks like proximity mechanism is different that usual one.

**Comment by ssaqua** [comment]
Sorry to hear 😞 I'll be removing again from supported devices list in that case. Thanks for trying it out.

**Comment by Iworb** [comment]
Okay, that's really sad. I miss this nifty service, it helped to save my battery on my previous phone :(
