### ISSUE TITLE
Feature request: Quick Settings Tile 7.0+

### ISSUE THREAD

**Issue by GreyAsteroid** [ssaqua/ProximityService#2]
Please consider adding a quick settings tile to activate/deactivate the service. This would also allow for a "hide icon from app drawer" option since the service could be activated without it.

**Comment by ssaqua** [comment]
Thanks for the suggestion. Will be looking at a quick settings option for a future version in addition to a number of other changes that I've been slowly working on. I'm unsure on implementing hiding from app drawer as this could be something that is better left to the user to customize with a launcher app. The default app icon launch action will also probably be changing to open a settings UI with other options for starting and stopping the service.

**Comment by ssaqua** [comment]
Added in #4 and available in the next version.
