### ISSUE TITLE
Flashing screen

### ISSUE THREAD

**Issue by JonnyTech** [ssaqua/ProximityService#7]
Running on Nokia 3 Android 8.0 the screen flashes on and off when the sensor is covered. Is there anything to try to do to fix it?

**Comment by ssaqua** [comment]
Is this happening on the latest version from the Play Store? Does it happen in both the default and AMOLED modes?

**Comment by JonnyTech** [comment]
Latest version from F-Droid. The AMOLED modes black out the screen. Are there any logs that can be retrieved?

**Comment by ssaqua** [comment]
There's no explicit log calls from the application itself so it would probably be difficult to diagnose that way. I suppose the best I can hope for would be for someone with the same problem or same device configuration to build the debug version and step through the service with a debugger.

**Comment by JonnyTech** [comment]
If you provide instructions then I can try, running Linux here so if you can direct me then I shall do it.

**Comment by ssaqua** [comment]
Great! 😃 

If you can get the project building with Android Studio then we would want to debug the app with the service active. If I am understanding correctly, only the default proximity sensor wakelock mode is having the issue?

https://github.com/ssaqua/ProximityService/blob/74997e1ae16500189272169a40c38c285718e0f0/app/src/main/kotlin/ss/proximityservice/ProximityService.kt#L265-L270

We would want to set breakpoints on the `wakeLock.acquire()` and `wakeLock.release()` lines and just see if there is anything strange happening like the wakeLock being released while the proximity sensor is still covered. It may also be helpful to set breakpoints on the first lines of the `onNear()` and `onFar()` functions for the same reasons.

**Comment by ssaqua** [comment]
There might be a potential solution here: https://dontkillmyapp.com/nokia

Closing this issue, please re-open or comment if there's anything new.

**Comment by JonnyTech** [comment]
I had discovered that and have all `evenwell` apps (user and system) disabled, but that does not fix the problem unfortunately.
